[build]
builder = "DOCKERFILE"
dockerfilePath = "./Dockerfile"

[deploy]
numReplicas = 1
restartPolicyType = "ON_FAILURE"

[[services]]
name = "web"
$default = true

[services.env]
SERVER_HOST = "0.0.0.0"
SERVER_PORT = "8080"

[services.ports]
port = 8080